[package]
name = "frontend"
version = "0.9.0"
authors = ["Marc Schreiber <marc.schreiber@aixigo.de>"]
repository = "https://github.com/aixigo/PREvant/"
edition = "2018"

[dependencies]
rocket = "0.4"
rocket_contrib = "0.4"
