version: "3"

services:
  api:
    image: aixigo/prevant
    network_mode: "bridge"
    userns_mode: "host"
    labels:
      traefik.frontend.rule: 'PathPrefix:/;'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  traefik:
    image: traefik
    command: --api --docker
    network_mode: "bridge"
    userns_mode: "host"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
