[package]
name = "prevant"
version = "0.9.0"
authors = ["Marc Schreiber <marc.schreiber@aixigo.de>"]
repository = "https://github.com/aixigo/PREvant/"
edition = "2018"

[dependencies]
crossbeam = "0.4"
crossbeam-utils = "0.5"
dkregistry = "0.2"
env_logger = "0.6"
failure = "0.1"
futures = "0.1"
handlebars = "1.1"
hyper = "0.10"
log = "0.4"
multimap = "0.4"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_yaml = "0.7"
tokio = "0.1"
tokio-core = "0.1"
toml = "0.4"
regex = "1.0"
rocket = "0.4"
rocket_contrib = "0.4"
rocket-cache-response = "0.5"
url = "1.7"

[dependencies.http-api-problem]
version = "0.12"
features = ["with_rocket"]

[dependencies.shiplift]
git = "https://github.com/schrieveslaach/shiplift.git"
rev = "00df424336b919184b8d0d26a85822589577913d"
default-features = false
features = ["unix-socket"]

[dependencies.goji]
git = "https://github.com/softprops/goji.git"
rev = "1d72ffee98b88321418181998225c700904be414"

[dependencies.reqwest]
version = "0.9.7"
default-features = false
features = ["rustls-tls"]
