[package]
name = "api"
version = "0.9.0"
authors = ["Marc Schreiber <marc.schreiber@aixigo.de>"]
repository = "https://github.com/aixigo/PREvant/"

[dependencies]
crossbeam = "0.4"
crossbeam-utils = "0.5"
failure = "0.1"
futures = "0.1"
goji = "0.2"
handlebars = "1.1"
hyper = "0.10"
log = "0.4"
multimap = "0.4"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_yaml = "0.7"
shiplift = "0.4"
tokio = "0.1"
toml = "0.4"
regex = "1.0"
rocket = "0.4"
rocket_contrib = "0.4"
url = "1.7"
