[package]
name = "api"
version = "0.9.0"
authors = ["Marc Schreiber <marc.schreiber@aixigo.de>"]
repository = "https://github.com/aixigo/PREvant/"

[dependencies]
crossbeam = "0.4"
crossbeam-utils = "0.5"
goji = "0.2"
hyper = "0.10"
log = "0.4"
multimap = "0.4"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_yaml = "0.7"
shiplift = { git = "https://github.com/softprops/shiplift", rev = "29bd95b42cd2b3c364f0be1f3e07e4b654e0ccf3" }
tokio = "0.1"
toml = "0.4"
regex = "1.0"
rocket = "0.4.0-rc.1"
rocket_codegen = "0.4.0-rc.1"
rocket_contrib = "0.4.0-rc.1"
url = "1.7"

